# Generated by Django 2.2.13 on 2020-06-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(default='covers/no_cover.jpg', upload_to='covers/'),
        ),
    ]
